### PR TITLE
Only show notifcation if tab doesn't have focus

### PR DESCRIPTION
**Pull request by Robdel12**
So I'm not quite sure how to test this. I'm more than willing to rebase & resubmit if needed!

### CODE REVIEW

**Comment by amercier** [comment]
First, thanks for proposing this PR, @Robdel12 :)

#### Multiple choices

While some people may agree with this behavior, I think some other people might not. Ideally, it would be preferable to turn this into a 3-choices selection:
- "Disabled" (default)
- "Always enabled"
- "Only if window is hidden"

[QUnit.urlConfig](http://api.qunitjs.com/QUnit.config/) allows multiple choices so it is definitely technically possible (even though we'll have to create the `<select>` ourselves).

However, this adds complexity to the UI so we need to discuss if it's the right thing to do, or not.

@bcardarella What's your opinion on this?

#### Browser support

All last versions of browser [support `window.hidden`](http://caniuse.com/#feat=hidden). However, we'll need to hide/disable the choice in case it's not.

#### Unit tests

I would be awesome to add unit tests for this before merging into *master*.

**Comment by bcardarella** [comment]
It is interesting, I'm thinking of something like IRCCloud. The behavior there is for the notification only be shown if the tab itself does not have focus. What value does one gain to show the notification if the have the tab currently open and are also watching the test suite?

The other side, however, would be to consider how this would affect people's current workflows. If they are using this library and expect to see the notification because that has been the behavior then an update changes this behavior that could be annoying.

I'd like to gather a few more opinions on this.

**Comment by rwjblue** [comment]
In general, I would want the notification only when not focused.  I'm totally fine with making it a three way selection, but I personally can't imagine the use case where a notification for the thing you actively have on screen is helpful....

**Comment by Robdel12** [comment]
@rwjblue That's what drove me to make the change. I didn't see it helpful to have the notifications while I was watching the tests run. 

I played with the idea of making it an option that you pass in with the config (like the other options) but couldn't think of a decent way to name it. Then I started thinking when would anyone want the notifications when viewing the tab? 

I'm not sure we need to complicate the UI. I see this more as a config you set once and leave it. Totally open to more opinions!

**Pull request closed without merging**
