### PR TITLE
Replace QUnit.url to fix QUnit 1.17.0.

### LINKED ISSUE #17: Toolbar not ready, making tests fail with QUnit < 1.16
Tests fail because QUnit Notifications fail to add itself to QUnit toolbar.

- OK with latest QUnit (v1.16)
- NOK with QUnit v1.15 (and probably below as well)

Thanks @mauricioac for reporting this.
Separated this issue from #4 and #15 for clearer tracking.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #17.

---

@amercier / @bcardarella - This fixes the issue (I confirmed in a project), but one of the Karma tests is hanging and I'm not 100% sure how to debug it. I pushed this to a branch in the main repo so one of y'all can fix up the tests (I am sorry, but I ran out of time....).

### CODE REVIEW

**Comment by amercier** [comment]
Thanks for this PR @rwjblue.
However, before merging, I need to investigate why this makes the tests fails.

**Comment by rwjblue** [comment]
@amercier - Thanks for taking a look!

**Comment by amercier** [comment]
@rwjblue I replaced your implementation of `generateQueryString` by QUnit's.

This allows to keep the checkbox behavior in-line with QUnit behavior: clicking adds `&notifications` to the URL (your function was adding `&notifications=true`). See **urlConfig** section in [QUnit documentation](http://api.qunitjs.com/QUnit.config/) for details.

**Comment by amercier** [comment]
Released in v0.0.6.

**Comment by rwjblue** [comment]
@amercier - Thanks for getting it fixed!

**Pull request merged**
